image: boilerteam:latest

stages:
  - ver
  - init
  - tests
  - deploy

ver:
  stage: ver
  script:
    - python --version
    - whoami

init:
  stage: init
  script:
    - apk add postgresql-dev --no-cache
    - pip install psycopg2-binary
    - pip install -r requirements.txt

run_tests:
  stage: tests
  script:
    - apk add postgresql-dev --no-cache
    - pip install psycopg2-binary
    - pip install -r requirements.txt
    - python tests.py

deploy_staging:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/flask-api-staging.git
    - git push heroku master
    - echo "Deployed to Staging Server https://boilerplate_checkiner.herokuapp.com"
  environment:
    name: staging
    url: https://boilerplate_checkiner.herokuapp.com/
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/boilerplate_checkiner.git
    - git push heroku master
    - echo "Deployed to Production Server https://boilerplate_checkiner.herokuapp.com"
  environment:
    name: production
    url: https://boilerplate_checkiner.herokuapp.com/
  when: manual
  only:
    - master
